In [1]:
import pandas as pd
pd.set_option('display.mpl_style', 'default')
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np

//anaconda/lib/python2.7/site-packages/IPython/core/interactiveshell.py:2885: FutureWarning:
mpl_style had been deprecated and will be removed in a future version.
Use `matplotlib.pyplot.style.use` instead.

  exec(code_obj, self.user_global_ns, self.user_ns)
//anaconda/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')

In [2]:
airportdrop = pd.read_json("airportdropoffs.json", orient="index")

In [3]:
airportdrop

,2010.0,2011.0,2012.0,2013.0,2014.0,2015.0
Airport,132548,133523,127838,93455,89637,83105
Allerton-Pelham Gardens,1717,1906,2070,2146,2120,2274
Annadale-Huguenot-Prince's Bay-Eltingville,233,210,271,241,255,213
Arden Heights,126,123,177,172,150,163
Astoria,49252,55408,60214,64338,66433,71279
Auburndale,3346,3656,3706,3738,3903,3924
Baisley Park,19927,21041,23481,24801,25714,31468
Bath Beach,2111,2199,2481,2317,2289,2496
Battery Park City-Lower Manhattan,165684,185723,197340,206945,203737,217520
Bay Ridge,15616,16774,18167,17764,18140,19080
Bayside-Bayside Hills,9016,9437,9751,9585,9372,10000
Bedford,13068,16808,21931,25611,28115,31548
Bedford Park-Fordham North,2342,2516,2827,2700,2707,2985
Bellerose,3384,3797,3933,3966,3878,4184
Belmont,2758,3027,3020,3102,2952,2940
Bensonhurst East,3810,4073,4619,4184,4106,4393
Bensonhurst West,5442,5729,6298,5917,5700,6022
Borough Park,6627,7023,7815,7715,7791,8338
Breezy Point-Belle Harbor-Rockaway Park-Broad Channel,248,244,258,224,243,254
Briarwood-Jamaica Hills,13077,13964,15163,15091,14709,15165
Brighton Beach,3780,4284,4707,4660,4507,4601
Bronxdale,1580,1603,1611,1615,1648,1880
Brooklyn Heights-Cobble Hill,32990,36943,38721,39243,38030,38434
Brownsville,3878,3998,4446,4390,4296,5294
Bushwick North,9115,12229,15973,18952,22072,25775
Bushwick South,14097,18377,22972,26058,29551,34701
Cambria Heights,4916,5557,5869,5513,5832,6719
Canarsie,10330,10700,12001,11097,11026,13149
Carroll Gardens-Columbia Street-Red Hook,32885,37934,41521,42098,40989,42519
Central Harlem North-Polo Grounds,15845,18391,21181,23969,26882,30039
...,...,...,...,...,...,...
Stuyvesant Town-Cooper Village,17637,19889,20717,23129,22838,23698
Sunset Park East,4101,4354,4792,4373,4524,4712
Sunset Park West,7892,10535,11787,11929,12015,12226
Todt Hill-Emerson Hill-Heartland Village-Lighthouse Hill,561,575,681,717,675,697
Turtle Bay-East Midtown,360042,396148,415524,452359,443563,433408
University Heights-Morris Heights,2040,2238,2697,2582,2473,2748
Upper East Side-Carnegie Hill,138178,149096,153786,151180,149755,152816
Upper West Side,181741,196229,206225,213129,205015,210166
Van Cortlandt Village,3062,3093,3333,3369,3488,3575
Van Nest-Morris Park-Westchester Square,1966,2128,2379,2335,2314,3044
Washington Heights North,15306,17070,18444,20063,21148,22541
Washington Heights South,18781,20309,23073,24924,25972,27921
West Brighton,1900,2050,2167,2123,2001,2030
West Concourse,3262,3279,3477,3513,3491,3649
West Farms-Bronx River,1515,1503,1647,1658,1667,1854
West New Brighton-New Brighton-St. George,698,721,703,720,758,786
West Village,138820,157269,165965,180315,170161,169977
Westchester-Unionport,1731,1802,1965,2065,1878,1988
Westerleigh,345,369,407,434,437,432
Whitestone,8578,8827,9234,9265,8805,9425
Williamsbridge-Olinville,2389,2440,2643,2606,2637,2942
Williamsburg,3137,3528,4941,5334,5279,5688
Windsor Terrace,8835,9937,10670,10983,10654,11741
Woodhaven,6984,7256,7977,8205,8431,9479
Woodlawn-Wakefield,2369,2458,2693,2673,2695,2852
Woodside,16957,18751,21513,21937,20711,21816
Yorkville,113903,126756,138823,143295,137996,141038
park-cemetery-etc-Bronx,741,920,1232,1224,983,985
park-cemetery-etc-Brooklyn,1025,1277,1525,1618,1457,1450
park-cemetery-etc-Queens,278,361,607,476,405,394

In [4]:
airportdrop[2010.0]=(airportdrop[2010.0]-airportdrop[2010.0].mean())/airportdrop[2010.0].std()
airportdrop[2011.0]=(airportdrop[2011.0]-airportdrop[2011.0].mean())/airportdrop[2011.0].std()
airportdrop[2012.0]=(airportdrop[2012.0]-airportdrop[2012.0].mean())/airportdrop[2012.0].std()
airportdrop[2013.0]=(airportdrop[2013.0]-airportdrop[2013.0].mean())/airportdrop[2013.0].std()
airportdrop[2014.0]=(airportdrop[2014.0]-airportdrop[2014.0].mean())/airportdrop[2014.0].std()
airportdrop[2015.0]=(airportdrop[2015.0]-airportdrop[2015.0].mean())/airportdrop[2015.0].std()

In [5]:
airportdrop.dropna(inplace=True)

In [6]:
airport95 = airportdrop[airportdrop<airportdrop.quantile(0.95)]
airport95.describe()

           2010.0      2011.0      2012.0      2013.0      2014.0      2015.0
count  182.000000  182.000000  182.000000  182.000000  182.000000  182.000000
mean    -0.162936   -0.165266   -0.166340   -0.167961   -0.165904   -0.164151
std      0.278328    0.277568    0.283619    0.275881    0.273183    0.273771
min     -0.322605   -0.325641   -0.334560   -0.334518   -0.335275   -0.339955
25%     -0.298325   -0.302589   -0.310754   -0.310848   -0.311435   -0.313906
50%     -0.258788   -0.262787   -0.271345   -0.273188   -0.273336   -0.272556
75%     -0.154268   -0.149250   -0.146986   -0.144536   -0.135645   -0.123973
max      1.392579    1.276843    1.298212    1.267641    1.233574    1.220380

In [7]:
airportdeltas = airport95.pct_change(axis = 1)
airportdeltas = airportdeltas.drop(2010.0, axis = 1)
airportdeltas.dropna()
airportdeltas.describe(percentiles=[0.05, 0.1, 0.5, 0.85, 0.9, 0.95])

           2011.0      2012.0      2013.0      2014.0      2015.0
count  182.000000  182.000000  181.000000  182.000000  182.000000
mean     0.022807    0.023249   -0.008444   -0.007123   -0.043929
std      0.292175    0.347221    0.186946    0.209602    0.352869
min     -3.012953   -3.405871   -2.073395   -0.778408   -3.784868
5%      -0.109572   -0.108909   -0.122442   -0.170859   -0.236387
10%     -0.022229   -0.063735   -0.066305   -0.100014   -0.099163
50%      0.015270    0.025421    0.001344    0.001265    0.007800
85%      0.048981    0.034125    0.022415    0.007620    0.015674
90%      0.070014    0.045207    0.040528    0.011141    0.018380
95%      0.228138    0.213447    0.088607    0.090891    0.077002
max      1.035241    2.605986    0.793355    2.113785    0.602267

In [8]:
largechange = airportdeltas[airportdeltas>=airportdeltas.quantile(0.95)]
largechange = largechange.dropna(how='all')
largechange.describe()

          2011.0     2012.0     2013.0     2014.0     2015.0
count  10.000000  10.000000  10.000000  10.000000  10.000000
mean    0.636155   0.672552   0.262078   0.436189   0.263869
std     0.348657   0.718984   0.248081   0.646022   0.218145
min     0.228169   0.213810   0.088607   0.091059   0.077764
25%     0.321393   0.300941   0.100912   0.101372   0.097361
50%     0.619034   0.476529   0.133935   0.141616   0.148530
75%     0.972546   0.543689   0.377343   0.363191   0.439504
max     1.035241   2.605986   0.793355   2.113785   0.602267

In [9]:
largechange.to_csv('highchangeairportwith20142015.csv')

In [10]:
airportdrop = pd.read_json("airportdropoffs.json", orient="index")

In [11]:
airportdrop = airportdrop.drop(2015.0, axis = 1)

In [12]:
airportdrop = airportdrop.drop(2014.0, axis = 1)

In [13]:
airportdrop

,2010.0,2011.0,2012.0,2013.0
Airport,132548,133523,127838,93455
Allerton-Pelham Gardens,1717,1906,2070,2146
Annadale-Huguenot-Prince's Bay-Eltingville,233,210,271,241
Arden Heights,126,123,177,172
Astoria,49252,55408,60214,64338
Auburndale,3346,3656,3706,3738
Baisley Park,19927,21041,23481,24801
Bath Beach,2111,2199,2481,2317
Battery Park City-Lower Manhattan,165684,185723,197340,206945
Bay Ridge,15616,16774,18167,17764
Bayside-Bayside Hills,9016,9437,9751,9585
Bedford,13068,16808,21931,25611
Bedford Park-Fordham North,2342,2516,2827,2700
Bellerose,3384,3797,3933,3966
Belmont,2758,3027,3020,3102
Bensonhurst East,3810,4073,4619,4184
Bensonhurst West,5442,5729,6298,5917
Borough Park,6627,7023,7815,7715
Breezy Point-Belle Harbor-Rockaway Park-Broad Channel,248,244,258,224
Briarwood-Jamaica Hills,13077,13964,15163,15091
Brighton Beach,3780,4284,4707,4660
Bronxdale,1580,1603,1611,1615
Brooklyn Heights-Cobble Hill,32990,36943,38721,39243
Brownsville,3878,3998,4446,4390
Bushwick North,9115,12229,15973,18952
Bushwick South,14097,18377,22972,26058
Cambria Heights,4916,5557,5869,5513
Canarsie,10330,10700,12001,11097
Carroll Gardens-Columbia Street-Red Hook,32885,37934,41521,42098
Central Harlem North-Polo Grounds,15845,18391,21181,23969
...,...,...,...,...
Stuyvesant Town-Cooper Village,17637,19889,20717,23129
Sunset Park East,4101,4354,4792,4373
Sunset Park West,7892,10535,11787,11929
Todt Hill-Emerson Hill-Heartland Village-Lighthouse Hill,561,575,681,717
Turtle Bay-East Midtown,360042,396148,415524,452359
University Heights-Morris Heights,2040,2238,2697,2582
Upper East Side-Carnegie Hill,138178,149096,153786,151180
Upper West Side,181741,196229,206225,213129
Van Cortlandt Village,3062,3093,3333,3369
Van Nest-Morris Park-Westchester Square,1966,2128,2379,2335
Washington Heights North,15306,17070,18444,20063
Washington Heights South,18781,20309,23073,24924
West Brighton,1900,2050,2167,2123
West Concourse,3262,3279,3477,3513
West Farms-Bronx River,1515,1503,1647,1658
West New Brighton-New Brighton-St. George,698,721,703,720
West Village,138820,157269,165965,180315
Westchester-Unionport,1731,1802,1965,2065
Westerleigh,345,369,407,434
Whitestone,8578,8827,9234,9265
Williamsbridge-Olinville,2389,2440,2643,2606
Williamsburg,3137,3528,4941,5334
Windsor Terrace,8835,9937,10670,10983
Woodhaven,6984,7256,7977,8205
Woodlawn-Wakefield,2369,2458,2693,2673
Woodside,16957,18751,21513,21937
Yorkville,113903,126756,138823,143295
park-cemetery-etc-Bronx,741,920,1232,1224
park-cemetery-etc-Brooklyn,1025,1277,1525,1618
park-cemetery-etc-Queens,278,361,607,476

In [14]:
airportdrop[2010.0]=(airportdrop[2010.0]-airportdrop[2010.0].mean())/airportdrop[2010.0].std()
airportdrop[2011.0]=(airportdrop[2011.0]-airportdrop[2011.0].mean())/airportdrop[2011.0].std()
airportdrop[2012.0]=(airportdrop[2012.0]-airportdrop[2012.0].mean())/airportdrop[2012.0].std()
airportdrop[2013.0]=(airportdrop[2013.0]-airportdrop[2013.0].mean())/airportdrop[2013.0].std()

In [15]:
airportdrop.dropna(inplace=True)

In [16]:
airport95 = airportdrop[airportdrop<airportdrop.quantile(0.95)]
airport95.describe()

           2010.0      2011.0      2012.0      2013.0
count  182.000000  182.000000  182.000000  182.000000
mean    -0.162936   -0.165266   -0.166340   -0.167961
std      0.278328    0.277568    0.283619    0.275881
min     -0.322605   -0.325641   -0.334560   -0.334518
25%     -0.298325   -0.302589   -0.310754   -0.310848
50%     -0.258788   -0.262787   -0.271345   -0.273188
75%     -0.154268   -0.149250   -0.146986   -0.144536
max      1.392579    1.276843    1.298212    1.267641

In [17]:
airportdeltas = airport95.pct_change(axis = 1)
airportdeltas = airportdeltas.drop(2010.0, axis = 1)
airportdeltas.dropna()
airportdeltas.describe(percentiles=[0.05, 0.1, 0.5, 0.85, 0.9, 0.95])

           2011.0      2012.0      2013.0
count  182.000000  182.000000  181.000000
mean     0.022807    0.023249   -0.008444
std      0.292175    0.347221    0.186946
min     -3.012953   -3.405871   -2.073395
5%      -0.109572   -0.108909   -0.122442
10%     -0.022229   -0.063735   -0.066305
50%      0.015270    0.025421    0.001344
85%      0.048981    0.034125    0.022415
90%      0.070014    0.045207    0.040528
95%      0.228138    0.213447    0.088607
max      1.035241    2.605986    0.793355

In [18]:
largechange = airportdeltas[airportdeltas>=airportdeltas.quantile(0.95)]
largechange = largechange.dropna(how='all')
largechange.describe()

          2011.0     2012.0     2013.0
count  10.000000  10.000000  10.000000
mean    0.636155   0.672552   0.262078
std     0.348657   0.718984   0.248081
min     0.228169   0.213810   0.088607
25%     0.321393   0.300941   0.100912
50%     0.619034   0.476529   0.133935
75%     0.972546   0.543689   0.377343
max     1.035241   2.605986   0.793355

In [19]:
largechange.to_csv('highchangeairportupto2013.csv')

In [20]:
airport95 = airportdrop[airportdrop<airportdrop.quantile(0.95)]
airport95.describe()

           2010.0      2011.0      2012.0      2013.0
count  182.000000  182.000000  182.000000  182.000000
mean    -0.162936   -0.165266   -0.166340   -0.167961
std      0.278328    0.277568    0.283619    0.275881
min     -0.322605   -0.325641   -0.334560   -0.334518
25%     -0.298325   -0.302589   -0.310754   -0.310848
50%     -0.258788   -0.262787   -0.271345   -0.273188
75%     -0.154268   -0.149250   -0.146986   -0.144536
max      1.392579    1.276843    1.298212    1.267641

In [21]:
airportdeltas = airport95.pct_change(axis = 1)
airportdeltas = airportdeltas.drop(2010.0, axis = 1)
airportdeltas.dropna()
airportdeltas.describe(percentiles=[0.05, 0.1, 0.5, 0.85, 0.9, 0.95])

           2011.0      2012.0      2013.0
count  182.000000  182.000000  181.000000
mean     0.022807    0.023249   -0.008444
std      0.292175    0.347221    0.186946
min     -3.012953   -3.405871   -2.073395
5%      -0.109572   -0.108909   -0.122442
10%     -0.022229   -0.063735   -0.066305
50%      0.015270    0.025421    0.001344
85%      0.048981    0.034125    0.022415
90%      0.070014    0.045207    0.040528
95%      0.228138    0.213447    0.088607
max      1.035241    2.605986    0.793355

In [22]:
largechange = airportdeltas[airportdeltas>=airportdeltas.quantile(0.90)]
largechange = largechange.dropna(how='all')
largechange.describe()

          2011.0     2012.0     2013.0
count  19.000000  19.000000  19.000000
mean    0.391822   0.403960   0.169125
std     0.363541   0.587253   0.202546
min     0.070507   0.045346   0.040528
25%     0.111600   0.096599   0.071584
50%     0.228169   0.213810   0.088607
75%     0.619034   0.476529   0.133935
max     1.035241   2.605986   0.793355

In [23]:
largechange.to_csv('highchangeairportupto201390pc.csv')